
lower: ${envId}
upper: ${ENVID}
token: token-${timestamp}

obj1:
  obj2:
    lower: ${envId}
    upper: ${ENVID}
    token: token-${timestamp}



list1:
  - ${envId}
  - ${ENVID}
  - token-${timestamp}
